//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandLine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandLine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        internal static string ActionPrompt {
            get {
                return ResourceManager.GetString("ActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string AmountPrompt {
            get {
                return ResourceManager.GetString("AmountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        internal static string APIKeyPrompt {
            get {
                return ResourceManager.GetString("APIKeyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        internal static string ClassPrompt {
            get {
                return ResourceManager.GetString("ClassPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create database.
        /// </summary>
        internal static string CreateDatabaseOption {
            get {
                return ResourceManager.GetString("CreateDatabaseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string DatePrompt {
            get {
                return ResourceManager.GetString("DatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get quote.
        /// </summary>
        internal static string GetQuoteOption {
            get {
                return ResourceManager.GetString("GetQuoteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New transaction.
        /// </summary>
        internal static string NewTransactionOption {
            get {
                return ResourceManager.GetString("NewTransactionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string PricePrompt {
            get {
                return ResourceManager.GetString("PricePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitOption {
            get {
                return ResourceManager.GetString("QuitOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        internal static string SelectAnOptionPrompt {
            get {
                return ResourceManager.GetString("SelectAnOptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set API Key.
        /// </summary>
        internal static string SetAPIKeyOption {
            get {
                return ResourceManager.GetString("SetAPIKeyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set price.
        /// </summary>
        internal static string SetPriceOption {
            get {
                return ResourceManager.GetString("SetPriceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string SymbolPrompt {
            get {
                return ResourceManager.GetString("SymbolPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID:.
        /// </summary>
        internal static string TransactionIDPrompt {
            get {
                return ResourceManager.GetString("TransactionIDPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update prices.
        /// </summary>
        internal static string UpdatePricesOption {
            get {
                return ResourceManager.GetString("UpdatePricesOption", resourceCulture);
            }
        }
    }
}
